image: golang:latest
cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/

build:
  stage: build
  before_script:
    - export GO111MODULE=on
  script:
    - go build .
    - ./import-boundary-checker

test:
  stage: test
  before_script:
    - export GO111MODULE=on
    - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.21.0
    - golangci-lint --version
  script:
    - golangci-lint run --timeout 1h
    - go test -cover -short $(go list ./... | grep -v /vendor/)
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
  needs: []

